In [1]:
import nltk
import pandas as pd
import numpy as np
import spacy as sp
import re

In [2]:
data = pd.read_csv('./dataset/hi-train.csv')
data.assign(text = data.text.str.replace('[^a-zA-Z0-9]', ''))
data.head()

/var/folders/0l/4kz4_s491vx7ql39ymh6w2280000gn/T/ipykernel_14869/241385024.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data.assign(text = data.text.str.replace('[^a-zA-Z0-9]', ''))


label                                               text
0     india  मेट्रो की इस लाइन के चलने से दक्षिणी दिल्ली से...
1  pakistan  नेटिजन यानि इंटरनेट पर सक्रिय नागरिक अब ट्विटर...
2      news  इसमें एक फ़्लाइट एटेनडेंट की मदद की गुहार है औ...
3     india  प्रतीक खुलेपन का, आज़ाद ख्याली का और भीड़ से अ...
4     india  ख़ासकर पिछले 10 साल तक प्रधानमंत्री रहे मनमोहन...

In [16]:
for i in range(len(data['text'])):
    file1 = open("./dataset/output.txt","a")
    file1.write(data['text'][i])
    file1.write("\n")
    file1.close()

In [18]:
# Remove all the empty lines from output.txt
with open("./output.txt") as infile, open("./output1.txt", "w") as outfile:
    for line in infile:
        if not line.strip(): continue  # skip the empty line
        outfile.write(line)  # non-empty line. Write it to output

In [3]:
data.shape

(3467, 2)

In [4]:
data.head()

label                                               text
0     india  मेट्रो की इस लाइन के चलने से दक्षिणी दिल्ली से...
1  pakistan  नेटिजन यानि इंटरनेट पर सक्रिय नागरिक अब ट्विटर...
2      news  इसमें एक फ़्लाइट एटेनडेंट की मदद की गुहार है औ...
3     india  प्रतीक खुलेपन का, आज़ाद ख्याली का और भीड़ से अ...
4     india  ख़ासकर पिछले 10 साल तक प्रधानमंत्री रहे मनमोहन...

In [19]:
data.to_csv("check.csv")

In [44]:
text_data = data['text']
type(text_data[1])

str

##### Text Preprocessing and Feature Extraction

In [45]:
from nltk.tokenize import word_tokenize
with open('./dataset/stopwords.txt', 'r') as f:
    stop_words = f.read().split('\n')
stop_words = set(stop_words)
print(stop_words)

{'बीच', '', 'कहाँ', 'हुए', 'पर', 'रहे', 'यही', 'अपने आप को', 'बहुत', 'अगर', 'में कुछ', 'अथवा', 'कौनसा', 'और', 'खुद को', 'उनकी', 'कुछ', 'जैसा', 'करता', 'ऐसे', 'निकल', 'रखें', 'दूसरे', 'हुई', 'नीचे', 'द्वारा', 'कम', 'दोनों', 'इसे', 'हुआ', 'खुद ही', 'दौरान', 'जब तक', 'उन्हें ', 'आज', 'किन्हें', 'सकते', 'किसे', 'मात्र', 'जा', 'जितना', 'से', 'जरा', 'जैसे', 'गए', 'मेरा', 'प्रत्येक', 'दूर', 'क्या', 'यह', 'जब', 'कहते', 'एक बार', 'या', 'की', 'काफ़ी', 'सो', 'लेकर', 'में कोई', 'हो', 'परंतु', 'खिलाफ', 'कर', 'है', 'सकती', 'करते', 'वहीं', 'भी', 'में', 'अन्य', 'अपना', 'इसके', 'कहा', 'होता', 'दुबारा', 'वग़ैरह', 'किया है', 'ज्यादा', 'रही', 'वहाँ', 'से अधिक', 'रहती', 'बिलकुल', 'पूरे', 'एस', 'मुझको', 'करने में', 'निहायत', 'रहा', 'स्थान', 'इनके', 'क्यों', 'कभी', 'मगर', 'इत्यादि', 'वर्ग', 'आपका', 'बंद', 'उनके', 'दूसरा', 'कितना', 'दिया', 'उस', 'बाहर', 'वह', 'वाले', 'किए', 'जो', '\ufeffके', 'किया', 'साबुत', 'बड़ा', 'इन्हें', 'आदि', 'अपने आप', 'गई', 'जाता', 'तब', 'को', 'इनकी', 'सभी', 'के माध्यम से', 'पूरा', 'स्

In [46]:
for i in range(len(text_data)):
    text_data[i] = text_data[i].replace('[^a-zA-Z0-9]', '')

In [47]:
# Tokenization
tokenized_text = []
for i in range(len(text_data)):
    tokenized_text.append(word_tokenize(text_data[i]))

In [48]:
tokenized_text[2]

['इसमें',
 'एक',
 'फ़्लाइट',
 'एटेनडेंट',
 'की',
 'मदद',
 'की',
 'गुहार',
 'है',
 'और',
 'साथ',
 'में',
 'डिक',
 'चेनी',
 'के',
 'उस',
 'निर्देश',
 'का',
 'ज़िक्र',
 'है',
 'जिसमें',
 'उन्होंने',
 'विमानों',
 'को',
 'मार',
 'गिराने',
 'की',
 'बात',
 'की',
 'थी.एक',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'की',
 'धमकियाँ',
 'भी',
 'सुनी',
 'जा',
 'सकती',
 'हैं',
 '.',
 'ये',
 'ऑडियो',
 '9/11',
 'आयोग',
 'के',
 'लिए',
 'तैयार',
 'किया',
 'गया',
 'था',
 '.',
 'ज़्यादातर',
 'बातें',
 'लिखित',
 'रूप',
 'में',
 'प्रकाशित',
 'की',
 'जा',
 'चुकी',
 'हैं.रिकॉर्डिंग',
 'में',
 'अमेरिकन',
 'एयरलाइन्स',
 'के',
 'फ़्लाइट',
 'नंबर',
 '11',
 'की',
 'फ़्लाइट',
 'एटेनडेंट',
 'बेटी',
 'का',
 'फ़ोन',
 'कॉल',
 'भी',
 'है.वे',
 'बोल',
 'रही',
 'हैं',
 ',',
 "''",
 'बिज़नस',
 'श्रेणी',
 'में',
 'किसी',
 'को',
 'स्टैब',
 'किया',
 'गया',
 'है',
 '.',
 'पता',
 'नहीं',
 ',',
 'लगता',
 'है',
 'कि',
 'हमारा',
 'अपहरण',
 'किया',
 'जा',
 'रहा',
 'है',
 '.',
 '``',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'को',
 'बोलते',
 'ह

In [49]:
# Stopwords removal
filtered_text = []
for i in range(len(tokenized_text)):
    temp = []
    for j in range(len(tokenized_text[i])):
        if tokenized_text[i][j] not in stop_words:
            temp.append(tokenized_text[i][j])
    filtered_text.append(temp)

In [50]:
filtered_text[2]

['फ़्लाइट',
 'एटेनडेंट',
 'मदद',
 'गुहार',
 'डिक',
 'चेनी',
 'के',
 'निर्देश',
 'ज़िक्र',
 'उन्होंने',
 'विमानों',
 'मार',
 'गिराने',
 'बात',
 'थी.एक',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'धमकियाँ',
 'सुनी',
 '.',
 'ऑडियो',
 '9/11',
 'आयोग',
 'के',
 'तैयार',
 '.',
 'ज़्यादातर',
 'बातें',
 'लिखित',
 'रूप',
 'प्रकाशित',
 'चुकी',
 'हैं.रिकॉर्डिंग',
 'अमेरिकन',
 'एयरलाइन्स',
 'के',
 'फ़्लाइट',
 'नंबर',
 '11',
 'फ़्लाइट',
 'एटेनडेंट',
 'बेटी',
 'फ़ोन',
 'कॉल',
 'है.वे',
 'बोल',
 ',',
 "''",
 'बिज़नस',
 'श्रेणी',
 'स्टैब',
 '.',
 'पता',
 'नहीं',
 ',',
 'लगता',
 'अपहरण',
 '.',
 '``',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'बोलते',
 'सना',
 ',',
 '``',
 'हिलेगा',
 'नहीं',
 ',',
 'सब',
 'ठीक',
 'रहेगा',
 '.',
 'कोशिश',
 'आपको',
 'नुकसान',
 'विमान',
 '.',
 'चुपचाप',
 'बैठे',
 'रहें',
 '.',
 '``',
 'ज़्यादातर',
 'रिकॉर्डिंग',
 'फ़ेडरल',
 'एविएशन',
 'एडमिनिस्ट्रेशन',
 '.',
 'विमान',
 'वर्ल्ड',
 'ट्रेड',
 'सेंटर',
 'टकरा',
 'चुका',
 'ऑडियो',
 'सुना',
 'कन्ट्रोलर',
 'विमान',
 'बात',
 'मैनहेटन',
 'है.ऑड

In [51]:
for i in range(len(filtered_text)):
    for j in range(len(filtered_text[i])):
        # filtered_text[i][j] = re.sub(r'\W', '', filtered_text[i][j])
        filtered_text[i][j] = re.sub(r'\d+', '', filtered_text[i][j])

In [52]:
# Remove . , ! ? `` '' etc
for i in range(len(filtered_text)):
    for j in range(len(filtered_text[i])):
        filtered_text[i][j] = re.sub(r'[.,!?;:/``]', '', filtered_text[i][j])
        filtered_text[i][j] = re.sub(r"''", '', filtered_text[i][j])
        filtered_text[i][j] = re.sub(r'``', '', filtered_text[i][j])
        

In [53]:
filtered_text[2]

['फ़्लाइट',
 'एटेनडेंट',
 'मदद',
 'गुहार',
 'डिक',
 'चेनी',
 'के',
 'निर्देश',
 'ज़िक्र',
 'उन्होंने',
 'विमानों',
 'मार',
 'गिराने',
 'बात',
 'थीएक',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'धमकियाँ',
 'सुनी',
 '',
 'ऑडियो',
 '',
 'आयोग',
 'के',
 'तैयार',
 '',
 'ज़्यादातर',
 'बातें',
 'लिखित',
 'रूप',
 'प्रकाशित',
 'चुकी',
 'हैंरिकॉर्डिंग',
 'अमेरिकन',
 'एयरलाइन्स',
 'के',
 'फ़्लाइट',
 'नंबर',
 '',
 'फ़्लाइट',
 'एटेनडेंट',
 'बेटी',
 'फ़ोन',
 'कॉल',
 'हैवे',
 'बोल',
 '',
 '',
 'बिज़नस',
 'श्रेणी',
 'स्टैब',
 '',
 'पता',
 'नहीं',
 '',
 'लगता',
 'अपहरण',
 '',
 '',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'बोलते',
 'सना',
 '',
 '',
 'हिलेगा',
 'नहीं',
 '',
 'सब',
 'ठीक',
 'रहेगा',
 '',
 'कोशिश',
 'आपको',
 'नुकसान',
 'विमान',
 '',
 'चुपचाप',
 'बैठे',
 'रहें',
 '',
 '',
 'ज़्यादातर',
 'रिकॉर्डिंग',
 'फ़ेडरल',
 'एविएशन',
 'एडमिनिस्ट्रेशन',
 '',
 'विमान',
 'वर्ल्ड',
 'ट्रेड',
 'सेंटर',
 'टकरा',
 'चुका',
 'ऑडियो',
 'सुना',
 'कन्ट्रोलर',
 'विमान',
 'बात',
 'मैनहेटन',
 'हैऑडियो',
 'आवाज़',
 'बोल',
 '',
 

In [54]:
# Remove words with length less than 2
for i in range(len(filtered_text)):
    temp = []
    for j in range(len(filtered_text[i])):
        if len(filtered_text[i][j]) > 1:
            temp.append(filtered_text[i][j])
    filtered_text[i] = temp

In [55]:
filtered_text[2]

['फ़्लाइट',
 'एटेनडेंट',
 'मदद',
 'गुहार',
 'डिक',
 'चेनी',
 'के',
 'निर्देश',
 'ज़िक्र',
 'उन्होंने',
 'विमानों',
 'मार',
 'गिराने',
 'बात',
 'थीएक',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'धमकियाँ',
 'सुनी',
 'ऑडियो',
 'आयोग',
 'के',
 'तैयार',
 'ज़्यादातर',
 'बातें',
 'लिखित',
 'रूप',
 'प्रकाशित',
 'चुकी',
 'हैंरिकॉर्डिंग',
 'अमेरिकन',
 'एयरलाइन्स',
 'के',
 'फ़्लाइट',
 'नंबर',
 'फ़्लाइट',
 'एटेनडेंट',
 'बेटी',
 'फ़ोन',
 'कॉल',
 'हैवे',
 'बोल',
 'बिज़नस',
 'श्रेणी',
 'स्टैब',
 'पता',
 'नहीं',
 'लगता',
 'अपहरण',
 'अपहरणकर्ता',
 'मोहम्मद',
 'अता',
 'बोलते',
 'सना',
 'हिलेगा',
 'नहीं',
 'सब',
 'ठीक',
 'रहेगा',
 'कोशिश',
 'आपको',
 'नुकसान',
 'विमान',
 'चुपचाप',
 'बैठे',
 'रहें',
 'ज़्यादातर',
 'रिकॉर्डिंग',
 'फ़ेडरल',
 'एविएशन',
 'एडमिनिस्ट्रेशन',
 'विमान',
 'वर्ल्ड',
 'ट्रेड',
 'सेंटर',
 'टकरा',
 'चुका',
 'ऑडियो',
 'सुना',
 'कन्ट्रोलर',
 'विमान',
 'बात',
 'मैनहेटन',
 'हैऑडियो',
 'आवाज़',
 'बोल',
 'विमान',
 'अभी-अभी',
 'वर्ल्ड',
 'ट्रेड',
 'सेंटर',
 'टकराया',
 'कहता',
 'पूरी',
 'इमारत',
 'बि

##### Stemming and Lemmatisation 

In [56]:
import pandas as pd
from snowballstemmer import stemmer

hindi_stem = stemmer('hindi')

def hindi_stemming(word):
    return hindi_stem.stemWord(word)

def remove_stop_words(query, stop_words):
    return [word for word in query if word not in stop_words]

def search_in_dataset(query, dataset):
    return [word for word in query if word in dataset]

In [57]:
def apply_suffix_rules(word):
    suffix_rules = [
        ("िय", "ी"), 
        ("ियां", "ी"), 
        ("िअों", "ी"), 
        ("यां", "ी"), 
        ("य", "ी"), 
        ("अों", ""), 
        ("ौं", ""), 
        ("े", ""), 
        ("ो", ""), 
        ("ों", ""), 
        ("ी", ""), 
        ("एँ", ""), 
        ("एं", ""), 
        ("ा", ""), 
        ("ं", ""), 
        ("ी", ""), 
        ("ए", "ा"), 
        ("ई", ""), 
        ("ना", ""), 
        ("ता", ""), 
        ("ती", ""), 
        ("जन", ""), 
        ("गण", ""), 
        ("तया", ""), 
        ("वग", ""), 
        ("कार", ""), 
        ("व", ""), 
        ("ें", ""), 
        ("ीय", ""), 
        ("़ियाँ", "या")
    ]
    
    for old_suffix, new_suffix in suffix_rules:
        if word.endswith(old_suffix):
            return word[:-len(old_suffix)] + new_suffix
    
    return word

In [58]:
# Stemming 
for i in range(len(filtered_text)):
    for j in range(len(filtered_text[i])):
        # filtered_text[i][j] = hindi_stemming(filtered_text[i][j])
        filtered_text[i][j] = apply_suffix_rules(filtered_text[i][j])


In [59]:
filtered_text[2]

['फ़्लाइट',
 'एटेनडेंट',
 'मदद',
 'गुहार',
 'डिक',
 'चेन',
 'क',
 'निर्देश',
 'ज़िक्र',
 'उन्होंन',
 'विमान',
 'मार',
 'गिरान',
 'बात',
 'थीएक',
 'अपहरणकर्त',
 'मोहम्मद',
 'अत',
 'धमकियाँ',
 'सुन',
 'ऑडिय',
 'आयोग',
 'क',
 'तैयार',
 'ज़्यादातर',
 'बाते',
 'लिखित',
 'रूप',
 'प्रकाशित',
 'चुक',
 'हैंरिकॉर्डिंग',
 'अमेरिकन',
 'एयरलाइन्स',
 'क',
 'फ़्लाइट',
 'नंबर',
 'फ़्लाइट',
 'एटेनडेंट',
 'बेट',
 'फ़ोन',
 'कॉल',
 'हैव',
 'बोल',
 'बिज़नस',
 'श्रेण',
 'स्टैब',
 'पत',
 'नही',
 'लगत',
 'अपहरण',
 'अपहरणकर्त',
 'मोहम्मद',
 'अत',
 'बोलत',
 'सन',
 'हिलेग',
 'नही',
 'सब',
 'ठीक',
 'रहेग',
 'कोशिश',
 'आपक',
 'नुकसान',
 'विमान',
 'चुपचाप',
 'बैठ',
 'रहे',
 'ज़्यादातर',
 'रिकॉर्डिंग',
 'फ़ेडरल',
 'एविएशन',
 'एडमिनिस्ट्रेशन',
 'विमान',
 'वर्ल्ड',
 'ट्रेड',
 'सेंटर',
 'टकर',
 'चुक',
 'ऑडिय',
 'सुन',
 'कन्ट्रोलर',
 'विमान',
 'बात',
 'मैनहेटन',
 'हैऑडिय',
 'आवाज़',
 'बोल',
 'विमान',
 'अभी-अभ',
 'वर्ल्ड',
 'ट्रेड',
 'सेंटर',
 'टकराय',
 'कहत',
 'पूर',
 'इमारत',
 'बिखर',
 'अफ़रा-तफ़र',
 'क',
 'आलम',
 'फ़ा

In [60]:
from gensim import corpora
from gensim.test.utils import get_tmpfile
dictionary = corpora.Dictionary(filtered_text)
print(dictionary)
dictionary.save('./dataset/dictionary.dict')
load_dict = corpora.Dictionary.load('./dataset/dictionary.dict')

# Create corpus
corpus = [dictionary.doc2bow(text) for text in filtered_text]
print(corpus[2])

from gensim import models
tfidf = models.TfidfModel(corpus)
corpus_tfidf = tfidf[corpus]
print(corpus_tfidf[2])


Dictionary<62525 unique tokens: ['अमेरिक', 'अरब', 'अलाव', 'आएग', 'आकर']...>
[(14, 5), (44, 2), (81, 3), (87, 1), (143, 1), (236, 2), (237, 1), (238, 2), (239, 1), (240, 1), (241, 1), (242, 1), (243, 1), (244, 1), (245, 1), (246, 1), (247, 1), (248, 1), (249, 1), (250, 1), (251, 1), (252, 2), (253, 1), (254, 1), (255, 1), (256, 2), (257, 1), (258, 1), (259, 1), (260, 1), (261, 1), (262, 1), (263, 1), (264, 1), (265, 1), (266, 1), (267, 1), (268, 1), (269, 1), (270, 1), (271, 2), (272, 1), (273, 2), (274, 1), (275, 1), (276, 1), (277, 2), (278, 1), (279, 1), (280, 1), (281, 1), (282, 1), (283, 2), (284, 1), (285, 1), (286, 1), (287, 1), (288, 1), (289, 1), (290, 1), (291, 1), (292, 1), (293, 1), (294, 1), (295, 1), (296, 3), (297, 3), (298, 1), (299, 1), (300, 1), (301, 1), (302, 1), (303, 2), (304, 1), (305, 1), (306, 1), (307, 1), (308, 1), (309, 1), (310, 1), (311, 2), (312, 1), (313, 1), (314, 1), (315, 1), (316, 1), (317, 1), (318, 1), (319, 2), (320, 1), (321, 6), (322, 1), (323, 1

##### PySpark Implementation for Distributed Processing

In [61]:
import json
import pandas as pd
import numpy as np

import sparknlp
import pyspark.sql.functions as F

from pyspark.ml import Pipeline
from pyspark.sql import SparkSession
from sparknlp.annotator import *
from sparknlp.base import *
from sparknlp.pretrained import PretrainedPipeline
from pyspark.sql.types import StringType, IntegerType

In [62]:
spark = sparknlp.start()

print("Spark NLP version: ", sparknlp.version())
print("Apache Spark version: ", spark.version)

Spark NLP version:  4.2.8
Apache Spark version:  3.3.0


In [63]:
from sparknlp import DocumentAssembler, Finisher 
from pyspark.ml import PipelineModel
from pyspark.sql import functions as F
from pyspark.sql import types as T

In [64]:
# Lemmatization using Spark NLP

document_assembler = DocumentAssembler() \
    .setInputCol("text") \
    .setOutputCol("document")

sentence_detector = SentenceDetector() \

tokenizer = Tokenizer() \

lemmatizer = LemmatizerModel.pretrained() \
    .setInputCols(["token"]) \
    .setOutputCol("lemma")

finisher = Finisher() \
    .setInputCols(["lemma"]) \
    .setOutputCols(["token_features"]) \
    .setOutputAsArray(True) \
    .setCleanAnnotations(False)

pipeline = PipelineModel(stages=[
    document_assembler, 
    sentence_detector, 
    tokenizer, 
    lemmatizer, 
    finisher
])

lemma_antbnc download started this may take some time.


Approximate size to download 907.6 KB
[OK!]


In [73]:
pipeline = Pipeline(stages=[document_assembler, tokenizer, lemmatizer])
example = spark.createDataFrame([filtered_text], ["text"])
result = pipeline.fit(example).transform(example)

AnalysisException: Cannot up cast input from "ARRAY<STRING>" to "STRING".
The type path of the target object is:
- root class: "java.lang.String"
You can either add an explicit cast to the input data or choose a higher precision type of the field in the target object

In [72]:
results.select(F.explode(F.arrays_zip(results.lemma.result)).alias("cols")) \
    .select(F.expr("cols['0']").alias("lemma")).show(truncate=False)

+-------------+
|lemma        |
+-------------+
|கட்சி        |
|வெற்றி       |
|பெற்றதோடு    |
|பெற்றத்      |
|ஓடு          |
|ஆட்சியில்    |
|உள்ள         |
|கட்சிக்கு    |
|ஒரு          |
|மாற்றுக்     |
|கட்சியாக     |
|வளர்ந்துள்ளது|
|வளர்ந்த்     |
|உள்ளது       |
+-------------+



##### POS Tagging and Named Entity Recognition

In [ ]:
from nltk.tag import tnt
from nltk.corpus import indian
import nltk
from nltk.tree import Tree

In [ ]:
def hindi_model():
    train_data = indian.tagged_sents('hindi.pos')
    tnt_pos_tagger = tnt.TnT()
    tnt_pos_tagger.train(train_data)
    return tnt_pos_tagger

model = hindi_model()
pos_tagged_text = []
for i in range(len(filtered_text[:2])):
    pos_tagged_text.append(model.tag(filtered_text[i]))


In [ ]:
pos_tagged_text[1]

[('नेटिजन', 'Unk'),
 ('यानि', 'CC'),
 ('इंटरनेट', 'Unk'),
 ('सक्रिय', 'JJ'),
 ('नागरिक', 'NN'),
 ('ट्विटर', 'Unk'),
 ('सरकार', 'NN'),
 ('लगाए', 'VFM'),
 ('प्रतिबंधों', 'NN'),
 ('के', 'PREP'),
 ('समर्थन', 'NVB'),
 ('विरोध', 'Unk'),
 ('विचार', 'Unk'),
 ('व्यक्त', 'JVB'),
 ('वेबसाइट', 'Unk'),
 ('संबंधी', 'Unk'),
 ('सूचना', 'NN'),
 ('जारी', 'JVB'),
 ('हैंकुछ', 'Unk'),
 ('दिन', 'NN'),
 ('शियाओं', 'Unk'),
 ('के', 'PREP'),
 ('खिलाफ़', 'Unk'),
 ('हिंसा', 'NN'),
 ('नज़र', 'Unk'),
 ('रखनेवाली', 'Unk'),
 ('प्रतिबंधित', 'Unk'),
 ('वेबसाइट', 'Unk'),
 ('शियाकिलिंगकॉम', 'Unk'),
 ('ट्विटर', 'Unk'),
 ('चलाए', 'Unk'),
 ('अभियान', 'Unk'),
 ('सड़कों', 'Unk'),
 ('प्रदर्शन', 'Unk'),
 ('के', 'PREP'),
 ('बहाल', 'JVB'),
 ('थाउससे', 'Unk'),
 ('दिन', 'NN'),
 ('अहमदिया', 'Unk'),
 ('संप्रदाय', 'Unk'),
 ('आधिकारिक', 'NNC'),
 ('वेबसाइट', 'Unk'),
 ('अलइस्लामओआरजी', 'Unk'),
 ('ब्लॉक', 'Unk'),
 ('ट्विटर', 'Unk'),
 ('अहमदिया', 'Unk'),
 ('शब्द', 'Unk'),
 ('काफी', 'INTF'),
 ('प्रचलित', 'Unk'),
 ('थापाकिस्तान', 'Unk'),
 ('

In [ ]:
def get_keywords(pos):
    grammar = r"""NP:{<NN.*>}"""
    chunkParser = nltk.RegexpParser(grammar)
    chunked = chunkParser.parse(pos)
    continuous_chunk = set()
    current_chunk = []
    for i in chunked:
        if type(i) == Tree:
            current_chunk.append(" ".join([token for token, pos in i.leaves()]))
        elif current_chunk:
            named_entity = " ".join(current_chunk)
            if named_entity not in continuous_chunk:
                continuous_chunk.add(named_entity)
                current_chunk = []
            else:
                continue
    return (continuous_chunk)

In [ ]:
print(get_keywords(new_tagged))

{'विदेश मंत्री', 'अमरीका', 'नागरिकों', 'अमरीका संयुक्त राष्ट्र', 'प्रस्ताव', 'इराक', 'प्रतिबंधों'}


##### Bag of Words Model and TF-IDF Model

In [ ]:
# Bag of Words

from sklearn.feature_extraction.text import CountVectorizer
corpus = []
for i in range(len(filtered_text)):
    corpus.append(' '.join(filtered_text[i]))
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


##### N-Gram Model and Perplexity

In [ ]:
from nltk import ngrams
from collections import Counter

def get_ngrams(text, n):
    n_grams = ngrams(text, n)
    return [ ' '.join(grams) for grams in n_grams]

def get_ngrams_freq(text, n):
    n_grams = ngrams(text, n)
    return Counter(n_grams)

for i in range(len(filtered_text[:100])):
    print(get_ngrams(filtered_text[i], 2))
    print(get_ngrams_freq(filtered_text[i], 2))

['मटर लइन', 'लइन चलन', 'चलन दकषण', 'दकषण दलल', 'दलल नएड', 'नएड जएग', 'जएग यतरय', 'यतरय रजव', 'रजव हउस', 'हउस हकर', 'हकर पडगलकन', 'पडगलकन मजट', 'मजट लइन', 'लइन महतवपरण', 'महतवपरण कयक', 'कयक डरइवलस', 'डरइवलस डरइवर', 'डरइवर मटर', 'मटर चलन', 'चलन यजन', 'यजन भरत', 'भरत पहल', 'पहल मटर', 'मटर डरइवर', 'डरइवर चलई', 'चलई जएग', 'जएग मटर', 'मटर तसर', 'तसर भरत', 'भरत पहल', 'पहल डरइवरलस', 'डरइवरलस तकनक', 'तकनक आएग', 'आएग दनय', 'दनय डरइवरलस', 'डरइवरलस मटर', 'मटर चलत', 'चलत डरइवरलस', 'डरइवरलस मटर', 'मटर सफल', 'सफल दकषण', 'दकषण करय', 'करय रजधन', 'रजधन डरइवलस', 'डरइवलस टरन', 'टरन कमयब', 'कमयब मटर', 'मटर जमन', 'जमन चलत', 'चलत डरइवर', 'डरइवर कबन', 'कबन यरप', 'यरप डनमरक', 'डनमरक सपन', 'सपन इटल', 'इटल फरस', 'फरस जरमन', 'जरमन हगर', 'हगर सवटजरलड', 'सवटजरलड बरटन', 'बरटन डरइवरलस', 'डरइवरलस मटर', 'मटर चलत', 'चलत जयद', 'जयद शहर', 'शहर मटर', 'मटर चलई', 'चलई अलव', 'अलव अमरक', 'अमरक कनड', 'कनड डरइवरलस', 'डरइवरलस टरन', 'टरन चलत', 'चलत बरजल', 'बरजल चइल', 'चइल मटर', 'मटर भरत', 'भरत पडस', 'पडस डरइवरलस', 'डरइवरलस मटर', '

In [ ]:
# Perplexity 
from nltk.lm import MLE
from nltk.lm.preprocessing import padded_everygram_pipeline
from nltk.lm import Vocabulary

train, vocab = padded_everygram_pipeline(2, filtered_text)
model = MLE(2)
model.fit(train, vocab)
test = filtered_text[100]
print(model.perplexity(test))

inf
